spring:
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/base?autoReconnect=true&useUnicode=true
      username: root
      password: root
    secondary:
      url: jdbc:mysql://localhost:3306/cat?autoReconnect=true&useUnicode=true
      username: root
      password: root
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
